import React, { useContext, useState } from 'react';
import Head from 'next/head'
import Layout from '../components/layout'
import { Button, Typography } from '@mui/material';
import { AuthContext } from '../contexts/AuthContext';

export default function Home() {
  const { currentUser } = useContext(AuthContext)
  return (
    <div>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Typography>Home</Typography>
        <Typography>A project from Hannah L, Patrick, Sofie, Alisa, Hannah S. and Duc</Typography>
        <Button
          onClick={() => {
            console.log(currentUser)
          }}
        >Seize my arm</Button>
      </Layout>
    </div>
  )
}