import React from 'react';
import Head from 'next/head'
import Layout from '../components/layout'
import { Typography } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Typography>Home</Typography>
        <Typography>A project from Hannah L, Patrick, Sofie, Alisa, Hannah S. and Duc</Typography>
      </Layout>
    </div>
  )
}