import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Mission Smile</h1>
      <p>A project from Hannah L, Patrick, Sofie, Alisa, Hannah S. and Duc</p>
      <Button variant='contained'>Hello World</Button>
      <p>Hallo Welt!</p>
    </div>
  )
}
